routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'guest'], function () {
    Route::get('/','JogoController@login');    
    Route::get('/login','JogoController@login')->name('login');
    Route::post('/login','JogoController@doLogin')->name('doLogin');
    Route::get('/register','JogoController@register')->name('register');
    Route::post('/register','JogoController@doRegister')->name('doRegister');
});



$router->group(['middleware' => 'auth'], function() {
    Route::get('/','JogoController@dashboard');
    Route::any('/find','JogoController@find')->name('find');
    Route::any('/logout','JogoController@doLogout')->name('doLogout');
    Route::resource('products','ProductController');
    Route::get('clients/find','ClientController@filter')->name('clients.find');
    Route::resource('clients','ClientController');
    Route::resource('orders','OrderController');
    Route::resource('transactions','TransactionController');
});

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Order;
use App\Transaction;
use App\Product;

class Client extends Model
{
    protected $fillable = [
        'name','email'
    ];

    public function orders(){
        return $this->hasMany(Order::class);
    }

    public function transactions(){
        return $this->hasMany(Transaction::class);
    }
    
    public function available(){
        $products = Product::all();

        $todas = [];
        foreach($products as $product){
            //array_push($total,nuevo);
            $orders = Order::where([
                ['product_id','=',$product->id],
                ['client_id','=',$this->id]
            ])->get();
            $obj = [
                'product'=>['id'=>$product->id,'name'=>$product->name,'value'=>$product->value],
                'amount'=>0
            ];
            foreach($orders as $order){
                $obj['amount'] += $order->amount;
            }
            if($obj['amount']>0){
                $transactions = Transaction::where([
                    ['product_id','=',$product->id],
                    ['client_id','=',$this->id]
                ])->get();
                foreach($transactions as $transaction){
                    $obj['amount'] -= $transaction->amount;
                }
                if($obj['amount']>0){
                    array_push($todas,$obj);
                }
            }
        }
        return $todas;
    }

    public function hasEnough($product,$amount){
        $orders = Order::where([
            ['product_id','=',$product->id],
            ['client_id','=',$this->id]
        ])->get();
        
        $responce = false;

        $available = 0;
        foreach($orders as $order){
            $available += $order->amount;
        }
        
        if($available > 0){
            $transactions = Transaction::where([
                ['product_id','=',$product->id],
                ['client_id','=',$this->id]
            ])->get();
            foreach($transactions as $transaction){
                $available -= $transaction->amount;
            }
            $responce = $available >= $amount; 
        }
        return $responce;
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::latest()->paginate(20);
  
        return view('clients.index',compact('clients'));
           // ->with('i', (request()->input('page', 1) - 1) * 20);
    }
   
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('clients.create');
    }
  
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'second_name'=>'required',
            'email' => 'required',
        ]);
  
        Client::create($request->all());
   
        return redirect()->route('clients.index')
                        ->with('success','Client created successfully.');
    }
   
    /**
     * Display the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $client)
    {
        $availables = $client->available();
        return view('clients.show',['client'=>$client,'availables'=>$availables]);
    }
   
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Client  $Client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        return view('clients.edit',compact('client'));
    }
  
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        $request->validate([
            'name' => 'required',
            'second_name'=>'required',
            'email' => 'required',
        ]);
  
        $client->update($request->all());
  
        return redirect()->route('clients.index')
                        ->with('success','Client updated successfully');
    }
  
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        $client->delete();
  
        return redirect()->route('clients.index')
                        ->with('success','Client deleted successfully');
    }

    public function filter(Request $request){
        $responce = null;
        if ($request->has('param') && strlen ($request->param)>0 ) {
            $clients = Client::query()->where(
                'name','LIKE',"%{$request->param}%"
            )->orWhere(
                'email','LIKE',"%{$request->param}%"
            )->paginate(20);
            return view('clients.index',compact('clients'));
        }else{
            $responce = redirect()->route('clients.index')->withErrors(['Sin parametros de busqueda']);
        }
        return $responce;
    }
}

resources/views/clients/create.blade.php
@extends('../layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Agregando nuevo cliente</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('clients.index') }}"> Back</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('clients.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Identificador:</strong>
                <input type="text" name="email" class="form-control" placeholder="Identificador">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/clients/edit.blade.php
@extends('../layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Editando cliento existente</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('clients.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('clients.update',$client->id) }}" method="POST">
        @csrf
        @method('PUT')
         <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $client->name }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Identificador:</strong>
                    <input type="text" name="email" value="{{ $client->email }}" class="form-control" placeholder="Identificador">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/clients/index.blade.php
@extends('../layout')
 
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="float-right">
                <form  method="GET" action="{{ route('clients.find') }}">
                    @csrf
                    <div class="form-row">
                        <div class="col">
                        <input type="text" size="35" name="param" class="form-control" value="{{ app('request')->input('param') }}" placeholder="Nombre o Email">
                        </div>
                        <div class="col">
                        <button type="submit" class="btn btn-primary">Buscar</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="pull-left">
                <h2>Lista de clientes existentes</h2>
            </div>
            <!--<div class="pull-right">
                <a class="btn btn-success" href="{{ route('clients.create') }}"> Create New Client</a>
            </div>-->
        </div>
    </div>
   
    @if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> Hemos encontrado algunos problemas.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered table-hover">
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Identificador</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($clients as $client)
        <tr>
            <td>{{ $client->id }}</td>
            <td>{{ $client->name }}</td>
            <td>{{ $client->email }}</td>
            <td>
                <form action="{{ route('clients.destroy',$client->id) }}" method="POST">
                <center>
   
                    <a class="btn btn-info" href="{{ route('clients.show',$client->id) }}">Mostar</a>
    
                    @if(Auth::user()->isAdmin)
                    <a class="btn btn-primary" href="{{ route('clients.edit',$client->id) }}">Editar</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Borrar</button>
                    @endif
                </center>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
    
    {!! $clients->links() !!}
      
@endsection

resources/views/clients/show.blade.php
@extends('../layout')
@section('content')

    <div class="float-right">
        <a class="btn btn-primary" href="{{ route('clients.index') }}">Listado de clientes</a>
    </div>
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Cliente: {{ $client->name }} </h2>
                <hr>
            </div>
            
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Identificador:</strong>
                {{ $client->email }}
            </div>
        </div>
    </div>
        
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> Hemos encontrado algunos problemas.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    
    <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6">
        <h5> Producto disponible </h5>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Producto</th>
                        <th>Valor</th>
                        <th>Cantidad</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($availables as $product)
                    <tr>
                        <td>{{ $product['product']['name'] }}</td>
                        <td>{{ $product['product']['value'] }}</td>
                        <td>{{ $product['amount'] }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class ="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                <h4> Entregar producto </h4>
                </div>
            </div>
            <div class="row">
                <form action="{{ route('transactions.store') }}" method="POST">
                    @csrf
                    <input type="hidden" name="client" value="{{ $client->id }}">
                    <input type="hidden" name="user" value="{{ Auth::user()->id }}">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <select name="product" class="custom-select custom-select-xs mb-3">
                            @foreach ($availables as $product)
                                <tr>
                                    <option value="{{ $product['product']['id'] }}">{{ $product['product']['name'] }}</option>
                                </tr>
                            @endforeach
                        </select>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" name="amount" placeholder="Cantidad a entregar" aria-label="Cantidad a entregar" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn-success btn" type="submit">Entregar</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
        <br>
        <hr>
        
        </div>
        
    </div>
   
    <div class="row">
        <div class="col-xs-4 col-sm-4 col-md-4">
        <h5> Compras realizadas </h5>
            <table class="table table-bordered table-hover table-sm " cellspacing="0" width="100%">
                <thead>
                    <tr>
			<th class="th-sm">#</th>
                        <th class="th-sm">Producto</th>
                        <th class="th-sm">Valor</th>
                        <th class="th-sm">Cantidad</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($client->orders as $order)
                    <tr>
                        <td>{{ $order->number }}</td>
                        <td>{{ $order->product->name }}</td>
                        <td>{{ $order->product->value }}</td>
                        <td>{{ $order->amount }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        
        <div class="col-xs-8 col-sm-8 col-md-8">
        <h5> Retiros realizados </h5>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Transaccion</th>
                        <th>Producto</th>
                        <th>Valor</th>
                        <th>Cantidad</th>
                        <th>Hora</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($client->transactions as $transaction)
                    <tr>
                        <td>{{ $transaction->id }}</td>
                        <td>{{ $transaction->product->name }}</td>
                        <td>{{ $transaction->product->value }}</td>
                        <td>{{ $transaction->amount }}</td>
                        <td>{{ $transaction->created_at }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    
@endsection