routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'guest'], function () {
    Route::get('/','JogoController@login');    
    Route::get('/login','JogoController@login')->name('login');
    Route::post('/login','JogoController@doLogin')->name('doLogin');
    Route::get('/register','JogoController@register')->name('register');
    Route::post('/register','JogoController@doRegister')->name('doRegister');
});



$router->group(['middleware' => 'auth'], function() {
    Route::get('/','JogoController@dashboard');
    Route::any('/find','JogoController@find')->name('find');
    Route::any('/logout','JogoController@doLogout')->name('doLogout');
    Route::resource('products','ProductController');
    Route::get('clients/find','ClientController@filter')->name('clients.find');
    Route::resource('clients','ClientController');
    Route::resource('orders','OrderController');
    Route::resource('transactions','TransactionController');
});

app/Order.php
<?php

namespace App;

use App\Client;
use App\Product;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable =[ 
        'number','amount'
    ];

    public function client(){
    	return $this->belongsTo(Client::class);
    }

    public function product(){
        return $this->belongsTo(Product::class);
    }

}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Order;
use App\Product;
use App\Client;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::latest()->paginate(30);
  
        return view('orders.index',compact('orders'))
            ->with('i', (request()->input('page', 1) - 1) * 30);
    }
   
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('orders.create');
    }
  
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'id' => 'required',
            'product'=>'required',
            'amount' => 'required',
            'client' => 'required'
        ]);
  
        $client = Client::find($request->client);
        $product = Product::find($request->product);

        $order = new Order;
        $order->id = $request->client;
        $order->amount = $request->amount;

        $order->client()->associate($client);
        $order->product()->associate($product);
        $order->save();
   
        return redirect()->route('orders.index')
                        ->with('success','Order created successfully.');
    }
   
    /**
     * Display the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        return view('orders.show',compact('order'));
    }
   
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        return view('orders.edit',compact('order'));
    }
  
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        $request->validate([
            'id' => 'required',
            'product'=>'required',
            'amount' => 'required',
            'client' => 'required'
        ]);
  
        $order->update($request->all());
  
        return redirect()->route('orders.index')
                        ->with('success','Order updated successfully');
    }
  
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        $order->delete();
  
        return redirect()->route('orders.index')
                        ->with('success','Order deleted successfully');
    }
}

resources/views/orders/create.blade.php
@extends('../layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Agregando nueva orden</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('orders.index') }}">Atras</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('orders.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <strong># de orden:</strong>
                <input type="text" name="id" class="form-control" placeholder="# orden">
            </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <strong>Producto:</strong>
                <input type="text" name="product" class="form-control" placeholder="Producto">
            </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <strong>Cantidad:</strong>
                <input type="text" name="amount" class="form-control" placeholder="Cantidad">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Cliente:</strong>
                <input type="text" name="client" class="form-control" placeholder="Cliente">
            </div>
        </div>
       
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Crear</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/orders/edit.blade.php
@extends('../layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Editando orden existente</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('orders.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('orders.update',$order->id) }}" method="POST">
        @csrf
        @method('PUT')
         <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <strong># de orden:</strong>
                    <input type="text" name="id" value="{{ $order->id }}" class="form-control" placeholder="Id" readonly>
                </div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <strong>Cliente</strong>
                    <input type="text" name="client" value="{{ $order->client }}" class="form-control" placeholder="Cliente">
                </div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <strong>Producto</strong>
                    <input type="text" name="product" value="{{ $order->product }}" class="form-control" placeholder="Producto">
                </div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <strong>Cantidad</strong>
                    <input type="text" name="amount" value="{{ $order->amount }}" class="form-control" placeholder="Cantidad">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Editar</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/orders/index.blade.php
@extends('../layout')
 
@section('content')

<div class="float-right">
    @if(Auth::user()->isAdmin)
        <a class="btn btn-success" href="{{ route('orders.create') }}">Crear nueva orden</a>
    @endif
</div>
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Lista de ordenes existentes</h2>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>Id</th>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Cliente</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($orders as $order)
        <tr>
            <td>{{ $order->id }}</td>
            <td><a class="btn btn-info" href="{{ route('products.show',$order->product->id) }}"> {{ $order->product->name }} </a></td>
            <td>{{ $order->amount }}</td>
            <td><a class="btn btn-info" href="{{ route('clients.show',$order->client->id) }}"> {{ $order->client->name." ".$order->client->second_name }} </a></td>
            <td>
                <form action="{{ route('orders.destroy',$order->id) }}" method="POST">
                    <center>
                    <a class="btn btn-info" href="{{ route('orders.show',$order->id) }}">Mostar</a>
                    @if(Auth::user()->isAdmin)
                    <a class="btn btn-primary" href="{{ route('orders.edit',$order->id) }}">Editar</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Borrar</button>
                    @endif
                    </center>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
    
    {!! $orders->links() !!}
      
@endsection

resources/views/orders/show.blade.php
@extends('../layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Orden {{ $order->id }}</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('orders.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <strong>Orden:</strong>
                {{ $order->number }}
            </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <strong>Cliente</strong>
                {{ $order->client }}
            </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <strong>Producto</strong>
                {{ $order->product }}
            </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <strong>Cantidad</strong>
                {{ $order->amount }}
            </div>
        </div>
    </div>
@endsection